/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.spring.dependency-management") version "1.1.7"
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:3.4.3")
    }
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.security)
    implementation(libs.com.project.template.logger.starter)
    implementation(libs.com.project.template.logger.jpa.starter)
    implementation(libs.com.project.template.logger.mongo.starter)
    implementation(libs.com.baomidou.mybatis.plus.spring.boot3.starter)
    implementation(libs.com.baomidou.mybatis.plus.jsqlparser.v4.v9)
    implementation(libs.com.baomidou.mybatis.plus.generator)
    implementation(libs.org.apache.velocity.velocity.engine.core)
    implementation(libs.org.projectlombok.lombok)
    implementation(libs.mysql.mysql.connector.j)
    implementation(libs.com.alibaba.druid.spring.boot.starter)
    implementation(libs.org.springframework.boot.spring.boot.starter.aop)
    implementation(libs.org.springframework.boot.spring.boot.configuration.processor)
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.org.apache.commons.commons.collections4)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.redis)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    implementation(libs.cn.idev.excel.fastexcel)
    implementation(libs.com.auth0.java.jwt)
    implementation(libs.org.springframework.boot.spring.boot.starter.mail)
    implementation(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    implementation(libs.com.google.guava.guava)
    implementation(libs.org.codehaus.janino.janino)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.junit.junit)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "com.project.template"
version = "1.0-SNAPSHOT"
description = "template"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
