server:
  port: 8250

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.120:3307/test1?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # 邮箱转发配置
  mail:
    username: 1174752357@qq.com
    password: qxpnolhjayulhhif
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 587
  # 配置中心
  config:
    activate:
      on-profile: dev

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl