server:
  port: 8250

spring:

  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.130:3306/template_mysql8?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  # spring data jpa自动创建表配置
  jpa:
    hibernate:
      ddl-auto: update
  # 配置中心
  config:
    activate:
      on-profile: dev
  data:
    # redis
    redis:
      password: 123456
      port: 6379
      host: 192.168.66.120
    # mongodb
    mongodb:
      host: 192.168.66.130
      port: 27017
      database: template


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1

knife4j:
  enable: true
  production: false

#springdoc:
#  api-docs:
#    enabled: true


template:
  # logger日志配置
  logger:
    # 是否开启日志(default:true)
    enable: true
    # 日志等级(default:INFO)
    level: INFO
    file:
      # 是否开启日志文件存储(default:false)
      enable: true
      # 日志文件名称(default:info.log)
      name: template.log
      # 日志文件路径(default:./log)
      path: ./log
      # 存储天数(default:30)
      history: 30
      # 归档压缩大小限制(default:10MB)
      size: 30MB
    # 添加日志记录排除路径
    excluded:
    # mongo日志记录相关配置
    mongo:
      # 是否开启mongo记录
      enable: true
      # 是否开启mongo记录的requestBody和responseBody
      body: false
    # 数据库日志记录相关配置
    jpa:
      # 是否开启数据库记录
      enable: true
      # 是否开启数据库记录的requestBody和responseBody
      body: true
  # MetaHandler控制器
  meta-handler:
    # meta-handler是否启用
    enable: true
    # 插入字段
    column: user_id
  # token配置
  token:
    # 加密盐配置
    sign-key: nan1mono
    # 过期时间配置(秒)
    expiration: 86400
  security:
    # 是否开启按钮查询权限
    button-enable: true
    # 路由白名单配置
    allow:
      uri: /v3/api-docs/**,/swagger-ui/**,/test/**,/doc.html,/login/auth,/**/*.css,/**/*.js,/favicon.ico
  # 密码试错设定
  pass-error:
    # 是否开启试错限制
    enable: true
    # 试错次数
    times: 10
    # 试错上限锁定时间（分钟）
    lock-minute: 10
  # 缓存设置
  cache:
    configuration:
      # 缓存类型：redis or local，默认使用本地缓存
      type: local





