server:
  port: 8250

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.120:3306/template_mysql8?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # 邮箱转发配置
  mail:
    username: 1174752357@qq.com
    password: qxpnolhjayulhhif
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 587
  # 配置中心
  config:
    activate:
      on-profile: dev


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1

knife4j:
  enable: true
  production: false

springdoc:
  api-docs:
    enabled: true

logging:
  # 日志级别
  level:
    root: info
  file:
    # 日志文件名格式
    name: ./logs/template.log
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ./logs/%d{yyyyMMdd}/cmhn.out.log.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB，这里为了测试归档，暂时设置为2KB)
      max-file-size: 100MB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 20

template:
  # MetaHandler控制器
  meta-handler:
    # meta-handler是否启用
    enable: true
    # 插入字段
    column: user_id
  # token配置
  token:
    # 加密盐配置
    sign-key: nan1mono
    # 过期时间配置(秒)
    expiration: 86400
  security:
    # 是否开启按钮查询权限
    button-enable: true
    # 路由白名单配置
    allow:
      uri: /v3/api-docs/**,/swagger-ui/**,/test/**,/doc.html,/login/auth



