server:
  port: 8250

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.130:3307/template_mysql8?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # 邮箱转发配置
  mail:
    username: 1174752357@qq.com
    password: qxpnolhjayulhhif
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 587
  # 配置中心
  config:
    activate:
      on-profile: dev


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1

knife4j:
  enable: true
  production: false

springdoc:
  api-docs:
    enabled: true

template:
  # MetaHandler控制器
  meta-handler:
    # meta-handler是否启用
    enable: true
    # 插入字段
    column: "nickname"
  # token配置
  token:
    # 加密盐配置
    sign-key: "nan1mono"
    # 过期时间配置(秒)
    expiration: 86400



